Repository kubevirt/vm-console-proxy, pull requests merged in 2023-03, with the labels that each got.

#8 fix: Update Kubevirt CR used by CI
  automation/e2e-functests/deploy-kubevirt.sh
Labels: dco-signoff: yes, size/S, approved, release-note-none, lgtm

#9 ci: fix image version in the released yaml bundle
  .github/workflows/release.yaml
Labels: dco-signoff: yes, size/S, approved, release-note-none, lgtm

#13 OWNERS: Add 0xFelix and lyarwood to the list of approvers
  OWNERS
Labels: dco-signoff: yes, approved, release-note-none, size/XS, lgtm

#11 doc: Add API example to documentation
  README.md
  docs/api.md
Labels: dco-signoff: yes, approved, release-note-none, size/M, lgtm

#15 doc: Update documentation
  README.md
  example-client/README.md
Labels: dco-signoff: yes, size/S, approved, release-note-none, lgtm

#14 fix: Improve functional tests
  tests/proxy_test.go
Labels: dco-signoff: yes, approved, release-note-none, size/M, lgtm

#7 fix: Run "go mod vendor" and "go mod tidy"
  go.mod
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
Labels: dco-signoff: yes, approved, release-note-none, size/L, lgtm
