Repository kubevirt/vm-console-proxy, pull requests merged in 2024-07, with the labels that each got.

#154 doc: enhance the README.md to include development instructions.
  README.md
Labels: dco-signoff: yes, approved, release-note-none, size/XS, ok-to-test, lgtm

#155 feat: enable multiarch build in the Dockerfile
  Dockerfile
Labels: dco-signoff: yes, size/S, approved, release-note-none, ok-to-test, lgtm

#156 fix: enable KUBECONFIG default for functest
  Makefile
Labels: dco-signoff: yes, approved, release-note-none, size/XS, ok-to-test, lgtm

#165 API: Improve API and increase version to v1
  api/v1/constants.go
  api/v1/types.go
  api/v1alpha1/types.go
  docs/api.md
  go.mod
  go.sum
  manifests/api_service.yaml
  manifests/config_map.yaml
  pkg/console/console.go
  pkg/console/service/service.go
  pkg/console/service/service_test.go
  pkg/console/tlsconfig/tlsconfig.go
  pkg/console/tlsconfig/tlsconfig_test.go
  tests/proxy_test.go
  tests/tests_suite_test.go
  tests/tlsconfig_test.go
  tests/user-role_test.go
  vendor/github.com/openshift/library-go/LICENSE
  vendor/github.com/openshift/library-go/pkg/crypto/OWNERS
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/github.com/openshift/library-go/pkg/crypto/rotation.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/authentication/user/doc.go
  vendor/k8s.io/apiserver/pkg/authentication/user/user.go
  vendor/modules.txt
Labels: release-note, dco-signoff: yes, approved, size/XXL, lgtm
