Repository kubevirt/vm-console-proxy, pull requests merged in 2024-01, with the labels that each got.

#75 feat: Add a Role that will be used by users
  manifests/kustomization.yaml.in
  manifests/user_role.yaml
  tests/user-role_test.go
Labels: release-note, dco-signoff: yes, approved, size/L, lgtm

#82 feat: configure dependabot
  .github/dependabot.yml
Labels: dco-signoff: yes, approved, release-note-none, size/M, lgtm

#86 Remove 'codingben' from OWNERS
  OWNERS
Labels: dco-signoff: yes, approved, release-note-none, size/XS, lgtm
