Repository kubevirt/vm-console-proxy, pull requests merged in 2025-01, with the labels that each got.

#226 deps: Update golang.org/x/* dependencies
  api/go.mod
  api/go.sum
  api/vendor/golang.org/x/net/LICENSE
  api/vendor/golang.org/x/net/http2/client_conn_pool.go
  api/vendor/golang.org/x/net/http2/config.go
  api/vendor/golang.org/x/net/http2/config_go124.go
  api/vendor/golang.org/x/net/http2/config_pre_go124.go
  api/vendor/golang.org/x/net/http2/frame.go
  api/vendor/golang.org/x/net/http2/http2.go
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/golang.org/x/net/http2/transport.go
  api/vendor/golang.org/x/net/http2/unencrypted.go
  api/vendor/golang.org/x/net/http2/write.go
  api/vendor/golang.org/x/text/LICENSE
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: dco-signoff: yes, approved, release-note-none, size/XXL, lgtm

#231 [release-v0.5] deps: Update jwt to fix security issue
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: dco-signoff: yes, approved, release-note-none, size/M, lgtm

#167 chore: add renovate config
  renovate.json
Labels: dco-signoff: yes, approved, release-note-none, size/L, lgtm

#245 feat: disable renovate's regular dependency updates
  renovate.json
Labels: dco-signoff: yes, approved, release-note-none, size/XS, lgtm

#248 chore: Update golang version to 1.23.2
  Dockerfile
  api/go.mod
  go.mod
  renovate.json
  vendor/modules.txt
Labels: dco-signoff: yes, size/S, approved, release-note-none, lgtm

#258 feat: simplify renovate config
  renovate.json
Labels: dco-signoff: yes, approved, release-note-none, size/M, lgtm

#274 fix: regex in renovate config
  renovate.json
Labels: dco-signoff: yes, approved, release-note-none, size/XS, lgtm
